import { ProductType } from "../types/redux/product";

export const productsData: ProductType[] = [
    {
        id: "1",
        Product_name: "Sản phẩm A",
        Product_sku: "SKU001",
        Product_description: "Mô tả sản phẩm A",
        Product_currency: "VND",
        Product_color: "Đỏ",
        Product_size: "M",
        Product_variantSku: "VAR001",
        Product_specifications: "Thông số kỹ thuật A",
        Product_price: 200000,
        Product_rating: 4.5,
        Product_count: 1200,
        Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-3-DBoXkV50.jpg", "https://uniqlo-staging.vercel.app/assets/blog-2-Cs10lpwB.jpg"],
        Product_isNewArrival: true,
        Product_isBestSeller: false,
        Product_isOnSale: true,
        categoryId: "cat001",
    },
    {
        id: "2",
        Product_name: "Sản phẩm B",
        Product_sku: "SKU002",
        Product_description: "Mô tả sản phẩm B",
        Product_currency: "VND",
        Product_color: "Xanh",
        Product_size: "L",
        Product_variantSku: "VAR002",
        Product_specifications: "Thông số kỹ thuật B",
        Product_price: 300000,
        Product_rating: 4.0,
        Product_count: 850,
        Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-1-BJTEceG3.jpg", "https://uniqlo-staging.vercel.app/assets/blog-1-BJTEceG3.jpg"],
        Product_isNewArrival: false,
        Product_isBestSeller: true,
        Product_isOnSale: false,
        categoryId: "cat002",
    },
    {
        id: "3",
        Product_name: "Sản phẩm C",
        Product_sku: "SKU003",
        Product_description: "Mô tả sản phẩm C",
        Product_currency: "VND",
        Product_color: "Vàng",
        Product_size: "S",
        Product_variantSku: "VAR003",
        Product_specifications: "Thông số kỹ thuật C",
        Product_price: 150000,
        Product_rating: 3.5,
        Product_count: 500,
        Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg", "https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg"],
        Product_isNewArrival: true,
        Product_isBestSeller: false,
        Product_isOnSale: true,
        categoryId: "cat003",
    },
    {
        id: "4",
        Product_name: "Sản phẩm D",
        Product_sku: "SKU004",
        Product_description: "Mô tả sản phẩm D",
        Product_currency: "VND",
        Product_color: "Trắng",
        Product_size: "M",
        Product_variantSku: "VAR004",
        Product_specifications: "Thông số kỹ thuật D",
        Product_price: 400000,
        Product_rating: 5.0,
        Product_count: 2000,
        Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg", "https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg"],
        Product_isNewArrival: false,
        Product_isBestSeller: true,
        Product_isOnSale: false,
        categoryId: "cat004",
    },
    {
        id: "5",
        Product_name: "Sản phẩm E",
        Product_sku: "SKU005",
        Product_description: "Mô tả sản phẩm E",
        Product_currency: "VND",
        Product_color: "Đen",
        Product_size: "L",
        Product_variantSku: "VAR005",
        Product_specifications: "Thông số kỹ thuật E",
        Product_price: 250000,
        Product_rating: 4.2,
        Product_count: 750,
        Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg", "https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg"],
        Product_isNewArrival: true,
        Product_isBestSeller: false,
        Product_isOnSale: true,
        categoryId: "cat005",
    },
    {
        id: "6",
        Product_name: "Sản phẩm F",
        Product_sku: "SKU006",
        Product_description: "Mô tả sản phẩm F",
        Product_currency: "VND",
        Product_color: "Xám",
        Product_size: "S",
        Product_variantSku: "VAR006",
        Product_specifications: "Thông số kỹ thuật F",
        Product_price: 180000,
        Product_rating: 3.8,
        Product_count: 300,
        Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg", "https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg"],
        Product_isNewArrival: false,
        Product_isBestSeller: true,
        Product_isOnSale: false,
        categoryId: "cat006",
    },
    {
        id: "7",
        Product_name: "Sản phẩm G",
        Product_sku: "SKU007",
        Product_description: "Mô tả sản phẩm G",
        Product_currency: "VND",
        Product_color: "Nâu",
        Product_size: "M",
        Product_variantSku: "VAR007",
        Product_specifications: "Thông số kỹ thuật G",
        Product_price: 320000,
        Product_rating: 4.6,
        Product_count: 950,
        Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg", "https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg"],
        Product_isNewArrival: true,
        Product_isBestSeller: false,
        Product_isOnSale: true,
        categoryId: "cat007",
    },
    // {
    //     id: "8",
    //     Product_name: "Sản phẩm H",
    //     Product_sku: "SKU008",
    //     Product_description: "Mô tả sản phẩm H",
    //     Product_currency: "VND",
    //     Product_color: "Xanh lá",
    //     Product_size: "L",
    //     Product_variantSku: "VAR008",
    //     Product_specifications: "Thông số kỹ thuật H",
    //     Product_price: 500000,
    //     Product_rating: 4.9,
    //     Product_count: 12000,
    //     Product_images: ["https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg", "https://uniqlo-staging.vercel.app/assets/blog-4-BGyfREhB.jpg"],
    //     Product_isNewArrival: false,
    //     Product_isBestSeller: true,
    //     Product_isOnSale: false,
    //     categoryId: "cat008",
    // },
];